"""create entries table

Revision ID: c9c324f1a4ab
Revises:
Create Date: 2024-09-14 07:06:18.049659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9c324f1a4ab"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "entries",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "concept",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "amount",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "due_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "CLOSED",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum(
                "ONE_TIME",
                "WEEKLY",
                "BI_WEEKLY",
                "MONTLY",
                "YEARLY",
                name="frequency",
            ),
            nullable=False,
        ),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "repeat_interval",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "repeated",
            sa.BOOLEAN(),
            nullable=True,
        ),
        sa.Column(
            "repeat_forever",
            sa.BOOLEAN(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        table_name="entries",
    )
    op.execute(
        sqltext="DROP TYPE IF EXISTS status",
    )
    op.execute(
        sqltext="DROP TYPE IF EXISTS frequency;",
    )
    # ### end Alembic commands ###
