[project]
name = "my-entries-frontend"
version = "0.1.3"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.9.2",
    "pydantic-settings>=2.6.0",
    "streamlit>=1.39.0",
]

[tool.uv]
dev-dependencies = ["python-dotenv[cli]>=1.0.1", "ruff>=0.7.0"]
