"""add concept column

Revision ID: 9ecd0a57bb68
Revises: c8015dac496b
Create Date: 2024-06-19 20:13:54.260752

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ecd0a57bb68"
down_revision: Union[str, None] = "c8015dac496b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("concept", sa.String(), nullable=True))
    op.execute(
        sqltext="UPDATE entries SET concept = ''",
    )
    op.alter_column(
        "entries",
        "concept",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "concept")
    # ### end Alembic commands ###
