"""add repeat_forever column

Revision ID: c8015dac496b
Revises: c3af754719ed
Create Date: 2024-06-18 19:09:39.963235

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8015dac496b"
down_revision: Union[str, None] = "c3af754719ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entries",
        sa.Column(
            "repeat_forever",
            sa.Boolean(),
            nullable=True,
        ),
    )
    op.execute(
        sqltext="UPDATE entries SET repeat_forever = FALSE",
    )
    op.alter_column(
        "entries",
        "repeat_forever",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "repeat_forever")
    # ### end Alembic commands ###
