"""add repeted column

Revision ID: ee05c59b0e4a
Revises: 9ecd0a57bb68
Create Date: 2024-06-19 20:27:09.584155

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee05c59b0e4a"
down_revision: Union[str, None] = "9ecd0a57bb68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entries",
        sa.Column(
            "repeated",
            sa.Boolean(),
            nullable=True,
        ),
    )
    op.execute(
        sqltext="UPDATE entries SET repeated = FALSE",
    )
    op.alter_column(
        "entries",
        "repeated",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "repeated")
    # ### end Alembic commands ###
